using System;
using System.Collections.Generic;

namespace PonyuDev.SherpaOnnx.Common.Platform
{
    /// <summary>
    /// Lists every file under StreamingAssets/SherpaOnnx/.
    /// Generated by the editor before build, consumed at runtime
    /// to copy files from APK to persistentDataPath on Android.
    /// </summary>
    [Serializable]
    public sealed class StreamingAssetsManifest
    {
        /// <summary>
        /// Fingerprint of the file set (e.g. "42_31457280").
        /// Used to skip re-extraction when already up-to-date.
        /// </summary>
        public string version;

        /// <summary>
        /// Relative paths from StreamingAssets root
        /// (e.g. "SherpaOnnx/tts-settings.json",
        ///  "SherpaOnnx/tts-models/profile/model.onnx").
        /// </summary>
        public List<string> files = new();
    }
}
